### ISSUE TITLE
gdsfactory integration?

### ISSUE THREAD

**Issue by joamatab** [tfp-photonics/neurop_invdes#1]
Great work!

how about integrating some of this work into gdsfactory?

we already support [Meep's adjoint optimization](https://gdsfactory.github.io/gdsfactory/notebooks/plugins/meep/001_meep_sparameters.html#Adjoint-Optimization) and would be great to expand with your work

we also added your paper and github link to [awesome photonics list](https://github.com/joamatab/awesome_photonics)

**Comment by yaugenst** [comment]
Hey, thanks for including it in the list, that's cool!

As for the gdsfactory integration -  sounds interesting. Although I am a bit unsure what this would look like in practice? It seems to me like gdsfactory is geared towards on-chip devices and mode calculations, this is not really a setting that we were considering in this work. I guess it is straightforward to train some models for planar devices, but the mode calculations would need to be performed somewhere else.

If you are happy with just poking around a bit with free-space scatterers, then you are welcome to use the pre-trained models that we provide - the most accurate ones are the 2D nets trained on 16k samples. The inverse design procedure would need to be tweaked a bit to support 2D though.
