### ISSUE TITLE
Not able to run the training script

### ISSUE THREAD

**Issue by anthony0727** [tfp-photonics/neurop_invdes#3]
Hi! I followed the instructions in README, but unable to run the training script.
Seems like something is missing in the h5 files with wrong key/value.
Could you help me with the issue?

for the data, I downloaded h5 files in `datasets/field_2d_ez` from OneDrive.
https://github.com/tfp-photonics/neurop_invdes?tab=readme-ov-file#data-availability

data directories and command
`python3 train_surrogates.py --data-dir data`
```
anthony@xeona6000:~/neurop_invdes$ tree data
data
├── test
│   └── fields_2d_ez_test.h5
└── train
    └── fields_2d_ez_train.h5
```

running above throws this error
```
Global seed set to 912374122
Traceback (most recent call last):
  File "/home/anthony/neurop_invdes/train_surrogates.py", line 168, in <module>
    main(parser.parse_args())
  File "/home/anthony/neurop_invdes/train_surrogates.py", line 20, in main
    data = FieldData(
  File "/home/anthony/neurop_invdes/fno_field_prediction/data/fno_unet_data.py", line 24, in __init__
    self.save_data_attrs()
  File "/home/anthony/neurop_invdes/fno_field_prediction/data/fno_unet_data.py", line 34, in save_data_attrs
    attrs["out_channels"] = len(data[0][self.hparams.label_key])
  File "/home/anthony/neurop_invdes/fno_field_prediction/data/fno_unet_data.py", line 111, in __getitem__
    return self._get(index)
  File "/home/anthony/neurop_invdes/fno_field_prediction/data/fno_unet_data.py", line 115, in _getitem
    sample = self._from_file(fp, uid)
  File "/home/anthony/neurop_invdes/fno_field_prediction/data/fno_unet_data.py", line 133, in _from_file
    x = torch.from_numpy(np.array(f[uid][self.data_key], dtype="f4"))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/anthony/.pyenv/versions/miniconda3-latest/envs/con/lib/python3.10/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to synchronously open object (object 'design' doesn't exist)"
```

Thanks!

**Comment by yaugenst** [comment]
Hi Anthony! Sorry about that, the data is labelled inconsistently... the 3D data uses `design` as the input label, the 2D data uses `permittivity`. To run the training on the 2D data, you need to call `python3 train_surrogates.py --data-dir data --data-key permittivity`.
Let me know if that fixes the issue!

**Comment by anthony0727** [comment]
It works like a charm!

One thing to note is that there's been breaking changes in `neuralop` library.
We may want to specify the version of it.
https://github.com/tfp-photonics/neurop_invdes/blob/f276d116fd0a039f91c341eb18451b15dfa95fa3/environment.yml#L22

For me, it worked with 0.1.x version
`pip install git+https://github.com/NeuralOperator/neuraloperator@3edd7e8`

Thanks alot!

**Comment by yaugenst** [comment]
That's great to hear - I've updated the default data key so this doesn't happen in the future. And thanks for the `neuralop` fix, I've pinned the version in the requirements. I think this wasn't pinned because we have our own FNO implementation here and the `neuralop` package was added later for the tensorized FNOs (which are not included in the paper).

**Comment by anthony0727** [comment]
Did including weight factorization improve the result? (probably its purpose serves for reduced num. of params. under same accuracy)

Currently I'm sticking to full weight matrix because taking a portion of rank, i.e. reduced number of basis, might be very susceptible to the domains, etc.

p.s.
I'm currently focusing on surrogate solvers for metasurface structures with its E field, and TFNO hasn't really worked so far.

I would really appreciate your comment!

**Comment by yaugenst** [comment]
> Did including weight factorization improve the result? (probably its purpose serves for reduced num. of params. under same accuracy)

Yes exactly, I actually ran a few experiments and had good success in 2D, but not so much in 3D. I didn't really investigate further though because I've stopped working on this project. You can find a little writeup about my TFNO results here: https://api.wandb.ai/links/tfp-photonics/r70ozns2

I think you're probably right in that the factorization does not help in the general case. If you're doing metasurfaces, there might be some smart ways to do weight sharing to try to model long- and short-range interactions. But then again it's ML, so the "smart" physical approach won't necessarily work...

**Comment by anthony0727** [comment]
I'm exactly tackling on different ranges of interactions.

Thanks for sharing your experience and insight!

Wish you the best
